[package]
name = "waypoint-desktop"
version.workspace = true
description = "Local-first activity video studio"
authors = ["Jared Stimpson"]
edition.workspace = true
license.workspace = true

[lib]
name = "waypoint_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
activity-core.workspace = true
map-assets.workspace = true
render-core.workspace = true
serde.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
